In [1]:
import pandas as pd 

fent = pd.read_csv('/Users/HudsonCavanagh/Dropbox/Capstone/fent_data/fent_mod.csv')
fent = fent.T
# fent.head()
fent.columns = fent.T.iloc[:,0]
# fent = fent.drop(['State'])
fent.iloc[:,5:]


def range_fixer(item):
    item_avg = []
    item = str(item)
    if "to" in item:
        a = item.split(" to ")[0]
        b = item.split(" to ")[1]
        item_avg.append(float(a))
        item_avg.append(float(b))
        a_1 = sum(item_avg)
        b_1 = len(item_avg)
        print (a_1/b_1)
        return (a_1/b_1)
    elif "no reports" in item:
        return 0

fent.loc['2013'] = fent.loc['2013'].apply(lambda x: range_fixer(x))                    
fent.loc['2014'] = fent.loc['2014'].apply(lambda x: range_fixer(x))
fent.loc['2013', 'USA(fent)'] = 934 # this should have been on source doc: https://docs.google.com/spreadsheets/d/1RWCVU7gapVDp3m54aJ30jIYkpoQ6AnoLHeb0gE_2bjI/edit#gid=1118416318
fent.loc['2013', 'USA(op)'] = 270981
#only have half of 2014 data available, so assuming that 0.49437% of fent and ops are discovered in second half of year, based on prior years
fent.loc['2014', 'USA(op)'] = 279704 #see above for methodology, from http://www.deadiversion.usdoj.gov/nflis/spec_rpt_opioids_2014.pdf
fent.loc['2014', 'USA(fent)'] = 2032 #includes both fentanyl and acetyl fentanyl, which was first reported in this year

25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
74.5
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
174.5
25.0
25.0
74.5
25.0
25.0
25.0
25.0
25.0
25.0
174.5
25.0
25.0
25.0
25.0
25.0
25.0
25.0
25.0
74.5
25.0
25.0
25.0
25.0
174.5
74.5
25.0
25.0
174.5
25.0
25.0
174.5
25.0
25.0
374.5
74.5
25.0
25.0
74.5
25.0
25.0
25.0
174.5
374.5
25.0
174.5
25.0
25.0
25.0
25.0
374.5
25.0
25.0
25.0
25.0
25.0
25.0
25.0
174.5
25.0
74.5
25.0
25.0

In [2]:
fent.head(15)

State,Perscrip(op),Percrip(fent),Growth_perscrip,USA(op),USA(fent),AL,AK,AZ,AR,CA,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
State,Perscrip(op),Percrip(fent),Growth_perscrip,USA(op),USA(fent),AL,AK,AZ,AR,CA,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
2003,67.04,1.37,NaN,187162,467.239,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,69.8,1.51,0.0411695,195198,487.301,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,73.44,1.57,0.052149,205937,514.111,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,77.17,1.71,0.0507898,216957,541.62,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,81.31,1.83,0.0536478,229256,572.324,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,84.34,1.87,0.0372648,238129,594.477,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009,83.7,1.72,-0.00758833,236336,590,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,NaN,NaN,NaN,257927,644,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,NaN,NaN,NaN,256623,624,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,NaN,NaN,NaN,267344,644,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,NaN,NaN,NaN,270981,934,25,25,25,25,25,...,25,25,25,25,25,174.5,25,25,25,25
2014,NaN,NaN,NaN,279704,2032,25,25,25,25,74.5,...,25,25,25,25,25,174.5,25,74.5,25,25

In [3]:
avg_state_13 = sum(fent.iloc[11,5:])/ len(fent.iloc[11,5:])
avg_state_13
# fent_convert = fent.loc['2013', 'USA(fent)']
years = ['2013', '2012','2011', '2010',  '2009','2008','2007','2006','2005','2004', '2003']
state_list = fent.iloc[:,5:].columns

for i in range(len(years)):
    for state in state_list:
        try:
            fent.loc[years[i+1], state] = (fent.loc[years[i+1], 'USA(fent)'] / fent.loc[years[0], 'USA(fent)'])* fent.loc[years[0], state]
        except:
            continue

# fent.loc['2012', 'AL'] = fent.loc['2012', 'USA(fent)'] * fent.loc['2013', 'AL']/ fent.loc['2013', 'USA(fent)']

# fent.loc['2014'] = fent.loc['2014'].apply(lambda x: range_fixer(x))

In [4]:
fent.head(15)

State,Perscrip(op),Percrip(fent),Growth_perscrip,USA(op),USA(fent),AL,AK,AZ,AR,CA,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
State,Perscrip(op),Percrip(fent),Growth_perscrip,USA(op),USA(fent),AL,AK,AZ,AR,CA,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
2003,67.04,1.37,NaN,187162,467.239,12.5064,12.5064,12.5064,12.5064,12.5064,...,12.5064,12.5064,12.5064,12.5064,12.5064,87.2947,12.5064,12.5064,12.5064,12.5064
2004,69.8,1.51,0.0411695,195198,487.301,13.0434,13.0434,13.0434,13.0434,13.0434,...,13.0434,13.0434,13.0434,13.0434,13.0434,91.0428,13.0434,13.0434,13.0434,13.0434
2005,73.44,1.57,0.052149,205937,514.111,13.761,13.761,13.761,13.761,13.761,...,13.761,13.761,13.761,13.761,13.761,96.0519,13.761,13.761,13.761,13.761
2006,77.17,1.71,0.0507898,216957,541.62,14.4973,14.4973,14.4973,14.4973,14.4973,...,14.4973,14.4973,14.4973,14.4973,14.4973,101.191,14.4973,14.4973,14.4973,14.4973
2007,81.31,1.83,0.0536478,229256,572.324,15.3192,15.3192,15.3192,15.3192,15.3192,...,15.3192,15.3192,15.3192,15.3192,15.3192,106.928,15.3192,15.3192,15.3192,15.3192
2008,84.34,1.87,0.0372648,238129,594.477,15.9121,15.9121,15.9121,15.9121,15.9121,...,15.9121,15.9121,15.9121,15.9121,15.9121,111.067,15.9121,15.9121,15.9121,15.9121
2009,83.7,1.72,-0.00758833,236336,590,15.7923,15.7923,15.7923,15.7923,15.7923,...,15.7923,15.7923,15.7923,15.7923,15.7923,110.23,15.7923,15.7923,15.7923,15.7923
2010,NaN,NaN,NaN,257927,644,17.2377,17.2377,17.2377,17.2377,17.2377,...,17.2377,17.2377,17.2377,17.2377,17.2377,120.319,17.2377,17.2377,17.2377,17.2377
2011,NaN,NaN,NaN,256623,624,16.7024,16.7024,16.7024,16.7024,16.7024,...,16.7024,16.7024,16.7024,16.7024,16.7024,116.582,16.7024,16.7024,16.7024,16.7024
2012,NaN,NaN,NaN,267344,644,17.2377,17.2377,17.2377,17.2377,17.2377,...,17.2377,17.2377,17.2377,17.2377,17.2377,120.319,17.2377,17.2377,17.2377,17.2377
2013,NaN,NaN,NaN,270981,934,25,25,25,25,25,...,25,25,25,25,25,174.5,25,25,25,25
2014,NaN,NaN,NaN,279704,2032,25,25,25,25,74.5,...,25,25,25,25,25,174.5,25,74.5,25,25

In [5]:
fent.reset_index(inplace=1)
fent['year']= fent['index']
fent.head()
fent_simple = fent[['year', 'USA(op)', 'USA(fent)']]
fent_simple = fent_simple.iloc[1:, :]
# fent_state = fent.iloc[:, 7:]
# fent_state = fent_state.T
# fent_state.columns = fent_state.loc['year']
# fent_state = fent_state.T
# fent.loc[:, 0].index = ['state']


# fent_state
# fent_rates = fent_state.groupby(by=['year', 'state']).sum()

In [6]:
fent_simple.to_csv('/Users/HudsonCavanagh/Dropbox/Capstone/non_cdc_data/drug_seizures_year.csv')