In [1]:
import pandas as pd
import numpy as np
#downloaded from https://www.census.gov/2010census/csv/pop_density.csv -- state level

pop_dense = pd.read_csv('/Users/HudsonCavanagh/Dropbox/Capstone/non_cdc_data/pop_density.csv')
pop_dense.head()

,# POPULATION DENSITY DATA PROVIDED BY U.S. CENSUS.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,# DENSITY EXPRESSED AS PEOPLE PER SQUARE MILE.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,# DENSITY RANKING EXPRESSED IN ORDER OF MOST D...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STATE_OR_REGION,1910_POPULATION,1920_POPULATION,1930_POPULATION,1940_POPULATION,1950_POPULATION,1960_POPULATION,1970_POPULATION,1980_POPULATION,1990_POPULATION,...,1920_RANK,1930_RANK,1940_RANK,1950_RANK,1960_RANK,1970_RANK,1980_RANK,1990_RANK,2000_RANK,2010_RANK
3,United States,92228531,106021568,123202660,132165129,151325798,179323175,203211926,226545805,248709873,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alabama,2138093,2348174,2646248,2832961,3061743,3266740,3444165,3893888,4040587,...,25,24,23,24,28,28,28,27,28,29

In [2]:
pop_dense_cols = pop_dense.iloc[2,:]
pop_dense = pop_dense.iloc[3:,:]
pop_dense.columns = pop_dense_cols 
# pop_dense.head()
pop_dense.columns

Index([u'STATE_OR_REGION', u'1910_POPULATION', u'1920_POPULATION',
       u'1930_POPULATION', u'1940_POPULATION', u'1950_POPULATION',
       u'1960_POPULATION', u'1970_POPULATION', u'1980_POPULATION',
       u'1990_POPULATION', u'2000_POPULATION', u'2010_POPULATION',
       u'1910_DENSITY', u'1920_DENSITY', u'1930_DENSITY', u'1940_DENSITY',
       u'1950_DENSITY', u'1960_DENSITY', u'1970_DENSITY', u'1980_DENSITY',
       u'1990_DENSITY', u'2000_DENSITY', u'2010_DENSITY', u'1910_RANK',
       u'1920_RANK', u'1930_RANK', u'1940_RANK', u'1950_RANK', u'1960_RANK',
       u'1970_RANK', u'1980_RANK', u'1990_RANK', u'2000_RANK', u'2010_RANK'],
      dtype='object', name=2)

In [19]:
def floater(item):
    item = str(item)
    item = item.replace(",", "")
    try:
        item = float(item)
    except:
        pass 
    return item

pop_dense.iloc[:,1:] = pop_dense.iloc[:,1:].applymap(lambda x: floater(x))

pop_dense['2005_dense'] = (pop_dense['2000_DENSITY'] + pop_dense['2010_DENSITY'])/2.0

In [20]:
type(pop_dense['2010_DENSITY'][3])

float

In [21]:
pop_dense['2005_dense']

3       83.55
4        91.1
5        1.15
6       50.75
7        53.7
8      228.25
9          45
10      720.7
11     431.45
12    9613.55
13      324.3
14     155.35
15      200.2
16      17.35
17      227.4
18     175.35
19      53.45
20       33.9
21     106.15
22     104.15
23       42.2
24      570.2
25      826.7
26      175.3
27       64.2
28       61.9
29      84.25
30        6.5
31      23.05
32       21.4
33      142.5
34    1169.85
35         16
36     406.95
37     180.85
38        9.5
39     280.05
40       52.5
41      37.75
42      279.2
43    1016.05
44      143.7
45      10.35
46     145.95
47      88.05
48       30.4
49         67
50      190.9
51      94.95
52      76.15
53        102
54       5.45
55     1100.3
Name: 2005_dense, dtype: object

## Found county level data from 2010 census, below

https://www.census.gov/popest/data/maps/2011/maps-county2011.csv

https://www.census.gov/popest/data/maps/2009/Maps-county2009.csv

-seems like the previous years follow the same url pattern

for each county, add three features:

- total population
- population growth (assuming low or negative is associated with mortality)
- population density

In [24]:
map_2011_dense = pd.read_csv('/Users/HudsonCavanagh/Dropbox/Capstone/non_cdc_data/maps-county2011.csv')
map_2011_dense.head(50)

,table with row headers in column B and column headers in rows 3 through 4 (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Table 3. Cumulative Estimates of Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,State FIPS Code,..Geographic Area,"April 1, 2010 Estimates Base",Population Estimates (as of July 1),NaN,"Change, April 1, 2010 to July 1, 2011",NaN,"Change, July 1, 2010 to July 1, 2011",NaN,"July 1, 2011",NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,2010,2011,Number,Percent,Number,Percent,Population Density,Area (Square Miles),NaN,NaN,NaN,NaN
4,00000,United States,"308,745,538","309,330,219","311,591,917","2,846,379",0.9,"2,261,698",0.7,88.2,"3,531,932",NaN,NaN,NaN,NaN
5,01000,.Alabama,"4,779,735","4,785,401","4,802,740","23,005",0.5,"17,339",0.4,94.8,"50,645",NaN,NaN,NaN,NaN
6,01001,..Autauga County,"54,571","54,637","55,267",696,1.3,630,1.2,93.0,594,NaN,NaN,NaN,NaN
7,01003,..Baldwin County,"182,265","183,259","186,717","4,452",2.4,"3,458",1.9,117.4,"1,590",NaN,NaN,NaN,NaN
8,01005,..Barbour County,"27,457","27,390","27,119",-338,-1.2,-271,-1.0,30.6,885,NaN,NaN,NaN,NaN
9,01007,..Bibb County,"22,919","22,880","22,766",-153,-0.7,-114,-0.5,36.6,623,NaN,NaN,NaN,NaN
10,01009,..Blount County,"57,322","57,387","57,677",355,0.6,290,0.5,89.5,645,NaN,NaN,NaN,NaN
11,01011,..Bullock County,"10,915","10,893","10,542",-373,-3.4,-351,-3.2,16.9,623,NaN,NaN,NaN,NaN
12,01013,..Butler County,"20,947","20,941","20,650",-297,-1.4,-291,-1.4,26.6,777,NaN,NaN,NaN,NaN
13,01015,..Calhoun County,"118,572","118,426","117,797",-775,-0.7,-629,-0.5,194.4,606,NaN,NaN,NaN,NaN
14,01017,..Chambers County,"34,215","34,143","33,939",-276,-0.8,-204,-0.6,56.9,597,NaN,NaN,NaN,NaN
15,01019,..Cherokee County,"25,989","25,997","26,057",68,0.3,60,0.2,47.1,554,NaN,NaN,NaN,NaN
16,01021,..Chilton County,"43,642","43,722","43,895",253,0.6,173,0.4,63.4,693,NaN,NaN,NaN,NaN
17,01023,..Choctaw County,"13,858","13,851","13,609",-249,-1.8,-242,-1.7,14.9,914,NaN,NaN,NaN,NaN
18,01025,..Clarke County,"25,840","25,776","25,695",-145,-0.6,-81,-0.3,20.7,"1,238",NaN,NaN,NaN,NaN
19,01027,..Clay County,"13,932","13,935","13,862",-70,-0.5,-73,-0.5,23.0,604,NaN,NaN,NaN,NaN
20,01029,..Cleburne County,"14,972","14,978","14,835",-137,-0.9,-143,-1.0,26.5,560,NaN,NaN,NaN,NaN
21,01031,..Coffee County,"49,948","50,167","50,526",578,1.2,359,0.7,74.4,679,NaN,NaN,NaN,NaN
22,01033,..Colbert County,"54,428","54,491","54,512",84,0.2,21,0.0,92.0,593,NaN,NaN,NaN,NaN
23,01035,..Conecuh County,"13,228","13,222","13,105",-123,-0.9,-117,-0.9,15.4,850,NaN,NaN,NaN,NaN
24,01037,..Coosa County,"11,537","11,458","10,713",-824,-7.1,-745,-6.5,16.5,651,NaN,NaN,NaN,NaN
25,01039,..Covington County,"37,765","37,800","38,058",293,0.8,258,0.7,36.9,"1,030",NaN,NaN,NaN,NaN
26,01041,..Crenshaw County,"13,906","13,878","13,911",5,0.0,33,0.2,22.8,609,NaN,NaN,NaN,NaN
27,01043,..Cullman County,"80,406","80,496","80,536",130,0.2,40,0.0,109.6,735,NaN,NaN,NaN,NaN
28,01045,..Dale County,"50,251","50,343","50,044",-207,-0.4,-299,-0.6,89.2,561,NaN,NaN,NaN,NaN
29,01047,..Dallas County,"43,820","43,792","43,332",-488,-1.1,-460,-1.1,44.3,979,NaN,NaN,NaN,NaN
30,01049,..DeKalb County,"71,109","71,122","71,375",266,0.4,253,0.4,91.8,777,NaN,NaN,NaN,NaN
31,01051,..Elmore County,"79,303","79,590","80,162",859,1.1,572,0.7,129.6,618,NaN,NaN,NaN,NaN
32,01053,..Escambia County,"38,319","38,295","38,095",-224,-0.6,-200,-0.5,40.3,945,NaN,NaN,NaN,NaN
33,01055,..Etowah County,"104,430","104,440","104,303",-127,-0.1,-137,-0.1,195.0,535,NaN,NaN,NaN,NaN
34,01057,..Fayette County,"17,241","17,250","17,182",-59,-0.3,-68,-0.4,27.4,628,NaN,NaN,NaN,NaN
35,01059,..Franklin County,"31,704","31,723","31,884",180,0.6,161,0.5,50.3,634,NaN,NaN,NaN,NaN
36,01061,..Geneva County,"26,790","26,828","26,781",-9,0.0,-47,-0.2,46.6,574,NaN,NaN,NaN,NaN
37,01063,..Greene County,"9,045","9,005","8,921",-124,-1.4,-84,-0.9,13.8,647,NaN,NaN,NaN,NaN
38,01065,..Hale County,"15,760","15,736","15,421",-339,-2.2,-315,-2.0,23.9,644,NaN,NaN,NaN,NaN
39,01067,..Henry County,"17,302","17,308","17,412",110,0.6,104,0.6,31.0,562,NaN,NaN,NaN,NaN
40,01069,..Houston County,"101,547","101,769","102,369",822,0.8,600,0.6,176.6,580,NaN,NaN,NaN,NaN
41,01071,..Jackson County,"53,226","53,175","53,291",65,0.1,116,0.2,49.4,"1,078",NaN,NaN,NaN,NaN
42,01073,..Jefferson County,"658,466","658,386","658,931",465,0.1,545,0.1,592.9,"1,111",NaN,NaN,NaN,NaN
43,01075,..Lamar County,"14,564","14,520","14,311",-253,-1.7,-209,-1.4,23.7,605,NaN,NaN,NaN,NaN
44,01077,..Lauderdale County,"92,709","92,727","92,781",72,0.1,54,0.1,139.0,668,NaN,NaN,NaN,NaN
45,01079,..Lawrence County,"34,339","34,328","34,117",-222,-0.6,-211,-0.6,49.4,691,NaN,NaN,NaN,NaN
46,01081,..Lee County,"140,247","140,784","143,468","3,221",2.3,2684,1.9,236.1,608,NaN,NaN,NaN,NaN
47,01083,..Limestone County,"82,782","83,239","85,369","2,587",3.1,2130,2.6,152.5,560,NaN,NaN,NaN,NaN
48,01085,..Lowndes County,"11,299","11,270","11,147",-152,-1.3,-123,-1.1,15.6,716,NaN,NaN,NaN,NaN
49,01087,..Macon County,"21,452","21,535","21,182",-270,-1.3,-353,-1.6,34.8,609,NaN,NaN,NaN,NaN